[22.05.2023] [10:18:15] INFO [main] com.qmetry.qaf.automation.core.ConfigurationManager (ConfigurationManager.java:170) - ISFW build info: {qaf-Type=core, qaf-Revision=0, qaf-Version=3.0, qaf-Build-Time=26-Jul-2020 22:16:34}
[22.05.2023] [10:18:15] INFO [main] com.qmetry.qaf.automation.core.ConfigurationManager (ConfigurationManager.java:222) - Resource dir: D:\Quantum-Starter-Kit-master\src\main\resources\common. Found property files to load: 1
[22.05.2023] [10:18:15] INFO [main] com.qmetry.qaf.automation.core.ConfigurationManager (ConfigurationManager.java:236) - Resource dir: D:\Quantum-Starter-Kit-master\src\main\resources\common. Found property files to load: 1
[22.05.2023] [10:18:15] INFO [main] com.qmetry.qaf.automation.step.client.gherkin.GherkinScenarioFactory (ScenarioFactory.java:76) - scenario.file.loc[Ljava.lang.String;@1e683a3e
[22.05.2023] [10:18:15] INFO [main] com.qmetry.qaf.automation.step.client.text.BehaviorScanner (GherkinFileParser.java:109) - loading feature file: D:\Quantum-Starter-Kit-master\src\main\resources\scenarios\01firstRun.feature
[22.05.2023] [10:18:15] INFO [main] com.qmetry.qaf.automation.step.client.text.BehaviorScanner (GherkinFileParser.java:109) - loading feature file: D:\Quantum-Starter-Kit-master\src\main\resources\scenarios\02sampleTestCase.feature
[22.05.2023] [10:18:15] INFO [main] com.qmetry.qaf.automation.step.client.text.BehaviorScanner (GherkinFileParser.java:109) - loading feature file: D:\Quantum-Starter-Kit-master\src\main\resources\scenarios\03createTest.feature
[22.05.2023] [10:18:15] INFO [main] com.qmetry.qaf.automation.step.client.text.BehaviorScanner (GherkinFileParser.java:109) - loading feature file: D:\Quantum-Starter-Kit-master\src\main\resources\scenarios\04apiAutomation.feature
[22.05.2023] [10:18:15] INFO [main] com.qmetry.qaf.automation.step.client.text.BehaviorScanner (GherkinFileParser.java:109) - loading feature file: D:\Quantum-Starter-Kit-master\src\main\resources\scenarios\05apiAutomation.feature
[22.05.2023] [10:18:15] INFO [main] com.qmetry.qaf.automation.step.client.text.BehaviorScanner (GherkinFileParser.java:109) - loading feature file: D:\Quantum-Starter-Kit-master\src\main\resources\scenarios\APITestAutomation.feature
[22.05.2023] [10:18:15] INFO [main] com.qmetry.qaf.automation.step.client.text.BehaviorScanner (GherkinFileParser.java:109) - loading feature file: D:\Quantum-Starter-Kit-master\src\main\resources\scenarios\appium.feature
[22.05.2023] [10:18:15] INFO [main] com.qmetry.qaf.automation.step.client.text.BehaviorScanner (GherkinFileParser.java:109) - loading feature file: D:\Quantum-Starter-Kit-master\src\main\resources\scenarios\Suitshealthdev.feature
[22.05.2023] [10:18:15] INFO [main] com.qmetry.qaf.automation.step.client.text.BehaviorScanner (GherkinFileParser.java:109) - loading feature file: D:\Quantum-Starter-Kit-master\src\main\resources\scenarios\webSearch.feature
[22.05.2023] [10:18:15] INFO [main] com.qmetry.qaf.automation.step.client.gherkin.GherkinScenarioFactory (ScenarioFactory.java:82) - total test found: 25
[22.05.2023] [10:18:16] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: User able to signin with userid and password - 
[22.05.2023] [10:18:16] INFO [TestNG] com.qmetry.qaf.automation.step.JavaStepFinder (JavaStepFinder.java:69) - pkg: com.qmetry.qaf.automation.step
[22.05.2023] [10:18:16] INFO [TestNG] com.qmetry.qaf.automation.step.JavaStepFinder (JavaStepFinder.java:69) - pkg: com.quantum.steps
[22.05.2023] [10:18:16] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:17] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:17] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given I set post to signin appliction service end point "signin" with arguments: [signin]
[22.05.2023] [10:18:25] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given I set post to signin appliction service end point "signin" with arguments: [signin]
[22.05.2023] [10:18:25] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: When I verify response mobile "9951991196" name "vishwaa" message "Successfully Logged In" displayed with arguments: [9951991196, vishwaa, Successfully Logged In]
[22.05.2023] [10:18:26] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: When I verify response mobile "9951991196" name "vishwaa" message "Successfully Logged In" displayed with arguments: [9951991196, vishwaa, Successfully Logged In]
[22.05.2023] [10:18:26] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Then I will receive valid response
[22.05.2023] [10:18:26] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Then I will receive valid response
[22.05.2023] [10:18:26] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: User able to signin with userid and password with status SUCCESS
[22.05.2023] [10:18:26] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: A Create new user with Signup end point - 
[22.05.2023] [10:18:26] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:26] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:26] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given  I set post new signup service end point "signup" with arguments: [signup]
[22.05.2023] [10:18:28] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given  I set post new signup service end point "signup" with arguments: [signup]
[22.05.2023] [10:18:28] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: When I verify message for new user signup "Successfully registered" with arguments: [Successfully registered]
[22.05.2023] [10:18:28] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: When I verify message for new user signup "Successfully registered" with arguments: [Successfully registered]
[22.05.2023] [10:18:28] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Then I will receive valid response
[22.05.2023] [10:18:28] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Then I will receive valid response
[22.05.2023] [10:18:28] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: A Create new user with Signup end point with status SUCCESS
[22.05.2023] [10:18:28] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: Existing user able to forgot existing password - 
[22.05.2023] [10:18:28] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:28] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:28] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given I set post to forgot password service end point "changeforgotpassword" with arguments: [changeforgotpassword]
[22.05.2023] [10:18:30] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given I set post to forgot password service end point "changeforgotpassword" with arguments: [changeforgotpassword]
[22.05.2023] [10:18:30] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: When I verify message for change forgot password "Successfully Updated" with arguments: [Successfully Updated]
[22.05.2023] [10:18:30] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: When I verify message for change forgot password "Successfully Updated" with arguments: [Successfully Updated]
[22.05.2023] [10:18:30] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Then I will receive valid response
[22.05.2023] [10:18:30] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Then I will receive valid response
[22.05.2023] [10:18:30] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: Existing user able to forgot existing password with status SUCCESS
[22.05.2023] [10:18:30] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: get add blood requestion request - 
[22.05.2023] [10:18:30] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:30] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:30] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given  I set post addbloodrequestio service end point "bloodrequisition" with arguments: [bloodrequisition]
[22.05.2023] [10:18:32] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given  I set post addbloodrequestio service end point "bloodrequisition" with arguments: [bloodrequisition]
[22.05.2023] [10:18:32] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: When I verify message for blood requisition "Successfully Created" with arguments: [Successfully Created]
[22.05.2023] [10:18:32] ERROR [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:83) - Failure Teststep: When I verify message for blood requisition "Successfully Created" with arguments: [Successfully Created]
io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202) ~[json-path-5.3.0.jar:?]
	at com.quantum.steps.ApiRegresstionTest.iVerifyMessageForBloodRequisition(ApiRegresstionTest.java:399) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:150) ~[qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:127) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:237) [qaf-3.0.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) [testng-6.10.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:778) [qaf-3.0.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:632) [qaf-3.0.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39) [testng-6.10.jar:?]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421) [testng-6.10.jar:?]
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) [testng-6.10.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'U', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:86) ~[groovy-json-4.0.6.jar:4.0.6]
	at groovy.json.JsonLexer$nextToken.call(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97) ~[json-path-5.3.0.jar:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000) ~[json-path-5.3.0.jar:?]
	... 33 more
[22.05.2023] [10:18:32] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: When I verify message for blood requisition "Successfully Created" with arguments: [Successfully Created]
[22.05.2023] [10:18:32] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: get add blood requestion request with status FAILURE
[22.05.2023] [10:18:32] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: Verify update profile of the user - 
[22.05.2023] [10:18:32] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:32] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:32] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given I set update profile for the user and the service end point "updateprofile" with arguments: [updateprofile]
[22.05.2023] [10:18:33] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given I set update profile for the user and the service end point "updateprofile" with arguments: [updateprofile]
[22.05.2023] [10:18:33] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: When I verify the message for updateprofile user as "Successfully Updated" with arguments: [Successfully Updated]
[22.05.2023] [10:18:33] ERROR [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:83) - Failure Teststep: When I verify the message for updateprofile user as "Successfully Updated" with arguments: [Successfully Updated]
io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202) ~[json-path-5.3.0.jar:?]
	at com.quantum.steps.ApiRegresstionTest.iVerifyTheMessageForUpdateprofileUserAs(ApiRegresstionTest.java:514) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:150) ~[qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:127) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:237) [qaf-3.0.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) [testng-6.10.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:778) [qaf-3.0.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:632) [qaf-3.0.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39) [testng-6.10.jar:?]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421) [testng-6.10.jar:?]
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) [testng-6.10.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'U', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:86) ~[groovy-json-4.0.6.jar:4.0.6]
	at groovy.json.JsonLexer$nextToken.call(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97) ~[json-path-5.3.0.jar:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000) ~[json-path-5.3.0.jar:?]
	... 33 more
[22.05.2023] [10:18:33] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: When I verify the message for updateprofile user as "Successfully Updated" with arguments: [Successfully Updated]
[22.05.2023] [10:18:33] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: Verify update profile of the user with status FAILURE
[22.05.2023] [10:18:33] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: Validate API endpoint for search for blood donor - 
[22.05.2023] [10:18:33] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:33] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:33] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given I get search for blood donor service end point "searchblooddonor" with arguments: [searchblooddonor]
[22.05.2023] [10:18:35] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given I get search for blood donor service end point "searchblooddonor" with arguments: [searchblooddonor]
[22.05.2023] [10:18:35] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: When I verify message for getbloodbanklist "Successfully Searched" with arguments: [Successfully Searched]
[22.05.2023] [10:18:35] ERROR [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:83) - Failure Teststep: When I verify message for getbloodbanklist "Successfully Searched" with arguments: [Successfully Searched]
io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202) ~[json-path-5.3.0.jar:?]
	at com.quantum.steps.ApiRegresstionTest.iVerifyMessageForGetbloodbanklist(ApiRegresstionTest.java:404) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:150) ~[qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:127) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:237) [qaf-3.0.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) [testng-6.10.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:778) [qaf-3.0.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:632) [qaf-3.0.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39) [testng-6.10.jar:?]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421) [testng-6.10.jar:?]
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) [testng-6.10.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'U', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:86) ~[groovy-json-4.0.6.jar:4.0.6]
	at groovy.json.JsonLexer$nextToken.call(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97) ~[json-path-5.3.0.jar:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000) ~[json-path-5.3.0.jar:?]
	... 33 more
[22.05.2023] [10:18:35] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: When I verify message for getbloodbanklist "Successfully Searched" with arguments: [Successfully Searched]
[22.05.2023] [10:18:35] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: Validate API endpoint for search for blood donor with status FAILURE
[22.05.2023] [10:18:35] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: Validate API endpoint for search blood bank - 
[22.05.2023] [10:18:35] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:35] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:35] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given I get list of blood bank with search condition service end point "searchbloodbank" with arguments: [searchbloodbank]
[22.05.2023] [10:18:36] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given I get list of blood bank with search condition service end point "searchbloodbank" with arguments: [searchbloodbank]
[22.05.2023] [10:18:36] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: When I verify message for getbloodbanklist "Successfully Searched" with arguments: [Successfully Searched]
[22.05.2023] [10:18:36] ERROR [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:83) - Failure Teststep: When I verify message for getbloodbanklist "Successfully Searched" with arguments: [Successfully Searched]
io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202) ~[json-path-5.3.0.jar:?]
	at com.quantum.steps.ApiRegresstionTest.iVerifyMessageForGetbloodbanklist(ApiRegresstionTest.java:404) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:150) ~[qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:127) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:237) [qaf-3.0.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) [testng-6.10.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:778) [qaf-3.0.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:632) [qaf-3.0.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39) [testng-6.10.jar:?]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421) [testng-6.10.jar:?]
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) [testng-6.10.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'U', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:86) ~[groovy-json-4.0.6.jar:4.0.6]
	at groovy.json.JsonLexer$nextToken.call(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97) ~[json-path-5.3.0.jar:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000) ~[json-path-5.3.0.jar:?]
	... 33 more
[22.05.2023] [10:18:36] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: When I verify message for getbloodbanklist "Successfully Searched" with arguments: [Successfully Searched]
[22.05.2023] [10:18:36] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: Validate API endpoint for search blood bank with status FAILURE
[22.05.2023] [10:18:36] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: Validate API endpoint for add emergency contact details - 
[22.05.2023] [10:18:36] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:36] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:36] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given I set post add new emergency contact service end point "addemergencycontact" with arguments: [addemergencycontact]
[22.05.2023] [10:18:38] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given I set post add new emergency contact service end point "addemergencycontact" with arguments: [addemergencycontact]
[22.05.2023] [10:18:38] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: When I verify message for addemergencycontact "Successfully Added" with arguments: [Successfully Added]
[22.05.2023] [10:18:38] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: When I verify message for addemergencycontact "Successfully Added" with arguments: [Successfully Added]
[22.05.2023] [10:18:38] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Then I will receive valid response
[22.05.2023] [10:18:38] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Then I will receive valid response
[22.05.2023] [10:18:38] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: Validate API endpoint for add emergency contact details with status SUCCESS
[22.05.2023] [10:18:38] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: Validate API endpoint for update emergency contact details - 
[22.05.2023] [10:18:38] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:38] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:38] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given I set post update new emergency contact service end point "updateemergencycontact" with arguments: [updateemergencycontact]
[22.05.2023] [10:18:39] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given I set post update new emergency contact service end point "updateemergencycontact" with arguments: [updateemergencycontact]
[22.05.2023] [10:18:39] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: When I verify message for updateemergencycontact "Successfully Updated" with arguments: [Successfully Updated]
[22.05.2023] [10:18:39] ERROR [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:83) - Failure Teststep: When I verify message for updateemergencycontact "Successfully Updated" with arguments: [Successfully Updated]
io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202) ~[json-path-5.3.0.jar:?]
	at com.quantum.steps.ApiRegresstionTest.iVerifyMessageForUpdateemergencycontact(ApiRegresstionTest.java:430) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:150) ~[qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:127) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:237) [qaf-3.0.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) [testng-6.10.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:778) [qaf-3.0.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:632) [qaf-3.0.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39) [testng-6.10.jar:?]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421) [testng-6.10.jar:?]
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) [testng-6.10.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'U', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:86) ~[groovy-json-4.0.6.jar:4.0.6]
	at groovy.json.JsonLexer$nextToken.call(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97) ~[json-path-5.3.0.jar:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000) ~[json-path-5.3.0.jar:?]
	... 33 more
[22.05.2023] [10:18:39] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: When I verify message for updateemergencycontact "Successfully Updated" with arguments: [Successfully Updated]
[22.05.2023] [10:18:39] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: Validate API endpoint for update emergency contact details with status FAILURE
[22.05.2023] [10:18:39] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: Validate emergency alert to the user - 
[22.05.2023] [10:18:39] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:39] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:39] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given I send emergency alert by service end point "sendEmergencyAlert" with arguments: [sendEmergencyAlert]
[22.05.2023] [10:18:40] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given I send emergency alert by service end point "sendEmergencyAlert" with arguments: [sendEmergencyAlert]
[22.05.2023] [10:18:40] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: When I verify the message for sendEmergencyAlert "Emergency alert Sent Successfully" with arguments: [Emergency alert Sent Successfully]
[22.05.2023] [10:18:40] ERROR [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:83) - Failure Teststep: When I verify the message for sendEmergencyAlert "Emergency alert Sent Successfully" with arguments: [Emergency alert Sent Successfully]
io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202) ~[json-path-5.3.0.jar:?]
	at com.quantum.steps.ApiRegresstionTest.iVerifyTheMessageForSendEmergencyAlert(ApiRegresstionTest.java:588) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:150) ~[qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:127) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:237) [qaf-3.0.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) [testng-6.10.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:778) [qaf-3.0.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:632) [qaf-3.0.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39) [testng-6.10.jar:?]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421) [testng-6.10.jar:?]
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) [testng-6.10.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'U', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:86) ~[groovy-json-4.0.6.jar:4.0.6]
	at groovy.json.JsonLexer$nextToken.call(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97) ~[json-path-5.3.0.jar:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000) ~[json-path-5.3.0.jar:?]
	... 33 more
[22.05.2023] [10:18:40] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: When I verify the message for sendEmergencyAlert "Emergency alert Sent Successfully" with arguments: [Emergency alert Sent Successfully]
[22.05.2023] [10:18:40] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: Validate emergency alert to the user with status FAILURE
[22.05.2023] [10:18:40] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: Validate check mobile number exists - 
[22.05.2023] [10:18:40] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:40] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:40] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given I get list of of all customer with service end point "getAllCustomerAddress" with arguments: [getAllCustomerAddress]
[22.05.2023] [10:18:42] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given I get list of of all customer with service end point "getAllCustomerAddress" with arguments: [getAllCustomerAddress]
[22.05.2023] [10:18:42] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given I send alert by service end point "checkmobile" with arguments: [checkmobile]
[22.05.2023] [10:18:42] ERROR [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:83) - Failure Teststep: Given I send alert by service end point "checkmobile" with arguments: [checkmobile]
io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202) ~[json-path-5.3.0.jar:?]
	at com.quantum.steps.ApiRegresstionTest.iSendAlertByServiceEndPoint(ApiRegresstionTest.java:594) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:150) ~[qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:127) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:237) [qaf-3.0.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) [testng-6.10.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:778) [qaf-3.0.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:632) [qaf-3.0.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39) [testng-6.10.jar:?]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421) [testng-6.10.jar:?]
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) [testng-6.10.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'U', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:86) ~[groovy-json-4.0.6.jar:4.0.6]
	at groovy.json.JsonLexer$nextToken.call(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97) ~[json-path-5.3.0.jar:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000) ~[json-path-5.3.0.jar:?]
	... 33 more
[22.05.2023] [10:18:42] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given I send alert by service end point "checkmobile" with arguments: [checkmobile]
[22.05.2023] [10:18:42] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: Validate check mobile number exists with status FAILURE
[22.05.2023] [10:18:42] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: To fetch the current theme settings - 
[22.05.2023] [10:18:42] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:42] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:42] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given I sent fetch by service end point "gettheme" with arguments: [gettheme]
[22.05.2023] [10:18:44] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given I sent fetch by service end point "gettheme" with arguments: [gettheme]
[22.05.2023] [10:18:44] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: When I verify the message for gettheme "Succesfully fetched data" with arguments: [Succesfully fetched data]
[22.05.2023] [10:18:44] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: When I verify the message for gettheme "Succesfully fetched data" with arguments: [Succesfully fetched data]
[22.05.2023] [10:18:44] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Then I will receive valid response
[22.05.2023] [10:18:44] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Then I will receive valid response
[22.05.2023] [10:18:44] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: To fetch the current theme settings with status SUCCESS
[22.05.2023] [10:18:44] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: To fetch the hospital list - 
[22.05.2023] [10:18:44] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:44] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:44] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given I sent alert by service end point "gethospitals" with arguments: [gethospitals]
[22.05.2023] [10:18:45] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given I sent alert by service end point "gethospitals" with arguments: [gethospitals]
[22.05.2023] [10:18:45] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: When I verify the message for gethospitals "Successfully Searched" with arguments: [Successfully Searched]
[22.05.2023] [10:18:45] ERROR [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:83) - Failure Teststep: When I verify the message for gethospitals "Successfully Searched" with arguments: [Successfully Searched]
io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202) ~[json-path-5.3.0.jar:?]
	at com.quantum.steps.ApiRegresstionTest.iVerifyTheMessageForGethospitals(ApiRegresstionTest.java:663) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:150) ~[qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:127) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:237) [qaf-3.0.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) [testng-6.10.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:778) [qaf-3.0.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:632) [qaf-3.0.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39) [testng-6.10.jar:?]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421) [testng-6.10.jar:?]
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) [testng-6.10.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'U', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:86) ~[groovy-json-4.0.6.jar:4.0.6]
	at groovy.json.JsonLexer$nextToken.call(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97) ~[json-path-5.3.0.jar:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000) ~[json-path-5.3.0.jar:?]
	... 33 more
[22.05.2023] [10:18:45] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: When I verify the message for gethospitals "Successfully Searched" with arguments: [Successfully Searched]
[22.05.2023] [10:18:45] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: To fetch the hospital list with status FAILURE
[22.05.2023] [10:18:45] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: To get inserted order details - 
[22.05.2023] [10:18:45] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:45] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:45] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given I get list of order details from service end point "getOrder" with arguments: [getOrder]
[22.05.2023] [10:18:47] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given I get list of order details from service end point "getOrder" with arguments: [getOrder]
[22.05.2023] [10:18:47] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Then I will receive valid response
[22.05.2023] [10:18:47] ERROR [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:83) - Failure Teststep: Then I will receive valid response
java.lang.AssertionError: expected [401] but found [200]
	at org.testng.Assert.fail(Assert.java:94) ~[testng-6.10.jar:?]
	at org.testng.Assert.failNotEquals(Assert.java:513) ~[testng-6.10.jar:?]
	at org.testng.Assert.assertEqualsImpl(Assert.java:135) ~[testng-6.10.jar:?]
	at org.testng.Assert.assertEquals(Assert.java:116) ~[testng-6.10.jar:?]
	at org.testng.Assert.assertEquals(Assert.java:389) ~[testng-6.10.jar:?]
	at org.testng.Assert.assertEquals(Assert.java:399) ~[testng-6.10.jar:?]
	at com.quantum.steps.ApiRegresstionTest.iWillReceiveValidResponse(ApiRegresstionTest.java:441) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:150) ~[qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:127) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:237) [qaf-3.0.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) [testng-6.10.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:778) [qaf-3.0.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:632) [qaf-3.0.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39) [testng-6.10.jar:?]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421) [testng-6.10.jar:?]
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) [testng-6.10.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[22.05.2023] [10:18:47] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Then I will receive valid response
[22.05.2023] [10:18:47] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: To get inserted order details with status FAILURE
[22.05.2023] [10:18:47] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: Validate API endpoint for get Blood Bank list - 
[22.05.2023] [10:18:47] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:47] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:47] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given I get list of blood bank service end point "getbloodbanks" with arguments: [getbloodbanks]
[22.05.2023] [10:18:48] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given I get list of blood bank service end point "getbloodbanks" with arguments: [getbloodbanks]
[22.05.2023] [10:18:48] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: When I verify message for getbloodbanklist "Successfully Searched" with arguments: [Successfully Searched]
[22.05.2023] [10:18:48] ERROR [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:83) - Failure Teststep: When I verify message for getbloodbanklist "Successfully Searched" with arguments: [Successfully Searched]
io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202) ~[json-path-5.3.0.jar:?]
	at com.quantum.steps.ApiRegresstionTest.iVerifyMessageForGetbloodbanklist(ApiRegresstionTest.java:404) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:150) ~[qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:127) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:237) [qaf-3.0.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) [testng-6.10.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:778) [qaf-3.0.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:632) [qaf-3.0.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39) [testng-6.10.jar:?]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421) [testng-6.10.jar:?]
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) [testng-6.10.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'U', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:86) ~[groovy-json-4.0.6.jar:4.0.6]
	at groovy.json.JsonLexer$nextToken.call(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97) ~[json-path-5.3.0.jar:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000) ~[json-path-5.3.0.jar:?]
	... 33 more
[22.05.2023] [10:18:48] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: When I verify message for getbloodbanklist "Successfully Searched" with arguments: [Successfully Searched]
[22.05.2023] [10:18:48] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: Validate API endpoint for get Blood Bank list with status FAILURE
[22.05.2023] [10:18:48] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: validate API endpoint for get product by id - 
[22.05.2023] [10:18:48] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:48] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:48] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given  I get product details by id service end point "getProduct?id=1" with arguments: [getProduct?id=1]
[22.05.2023] [10:18:49] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given  I get product details by id service end point "getProduct?id=1" with arguments: [getProduct?id=1]
[22.05.2023] [10:18:49] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: When I verify the product "1" details from the response. with arguments: [1]
[22.05.2023] [10:18:49] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: When I verify the product "1" details from the response. with arguments: [1]
[22.05.2023] [10:18:49] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Then I will receive valid response
[22.05.2023] [10:18:49] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Then I will receive valid response
[22.05.2023] [10:18:49] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: validate API endpoint for get product by id with status SUCCESS
[22.05.2023] [10:18:49] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: validate API endpoint for get productlist with limit and offset parameters - 
[22.05.2023] [10:18:49] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:49] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:49] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given  I get product details by id service end point "getProductList?limit=1&offset=0" with arguments: [getProductList?limit=1&offset=0]
[22.05.2023] [10:18:51] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given  I get product details by id service end point "getProductList?limit=1&offset=0" with arguments: [getProductList?limit=1&offset=0]
[22.05.2023] [10:18:51] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: When I verify the limit "1"  and offset "0" details from the response. with arguments: [1, 0]
[22.05.2023] [10:18:51] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: When I verify the limit "1"  and offset "0" details from the response. with arguments: [1, 0]
[22.05.2023] [10:18:51] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Then I will receive valid response
[22.05.2023] [10:18:51] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Then I will receive valid response
[22.05.2023] [10:18:51] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: validate API endpoint for get productlist with limit and offset parameters with status SUCCESS
[22.05.2023] [10:18:51] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: Get saveyo details from the service endpoint - 
[22.05.2023] [10:18:51] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:51] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:51] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given I get savyo details list from service end point "getSaveyoDetails" with arguments: [getSaveyoDetails]
[22.05.2023] [10:18:52] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given I get savyo details list from service end point "getSaveyoDetails" with arguments: [getSaveyoDetails]
[22.05.2023] [10:18:52] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Then I will receive valid response
[22.05.2023] [10:18:52] ERROR [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:83) - Failure Teststep: Then I will receive valid response
java.lang.AssertionError: expected [401] but found [200]
	at org.testng.Assert.fail(Assert.java:94) ~[testng-6.10.jar:?]
	at org.testng.Assert.failNotEquals(Assert.java:513) ~[testng-6.10.jar:?]
	at org.testng.Assert.assertEqualsImpl(Assert.java:135) ~[testng-6.10.jar:?]
	at org.testng.Assert.assertEquals(Assert.java:116) ~[testng-6.10.jar:?]
	at org.testng.Assert.assertEquals(Assert.java:389) ~[testng-6.10.jar:?]
	at org.testng.Assert.assertEquals(Assert.java:399) ~[testng-6.10.jar:?]
	at com.quantum.steps.ApiRegresstionTest.iWillReceiveValidResponse(ApiRegresstionTest.java:441) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:150) ~[qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:127) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:237) [qaf-3.0.0.jar:?]
	at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) [testng-6.10.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:778) [qaf-3.0.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:632) [qaf-3.0.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39) [testng-6.10.jar:?]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421) [testng-6.10.jar:?]
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) [testng-6.10.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[22.05.2023] [10:18:52] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Then I will receive valid response
[22.05.2023] [10:18:52] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: Get saveyo details from the service endpoint with status FAILURE
[22.05.2023] [10:18:52] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: User update the order status - 
[22.05.2023] [10:18:52] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:52] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:52] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given User able to update the order "updateOrderStatus" with arguments: [updateOrderStatus]
[22.05.2023] [10:18:54] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given User able to update the order "updateOrderStatus" with arguments: [updateOrderStatus]
[22.05.2023] [10:18:54] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: When I verify message for updateOrderStatus "Order status updated successfully." with arguments: [Order status updated successfully.]
[22.05.2023] [10:18:54] ERROR [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:83) - Failure Teststep: When I verify message for updateOrderStatus "Order status updated successfully." with arguments: [Order status updated successfully.]
io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202) ~[json-path-5.3.0.jar:?]
	at com.quantum.steps.ApiRegresstionTest.iVerifyMessageForUpdateOrderStatus(ApiRegresstionTest.java:556) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:150) ~[qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:127) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:237) [qaf-3.0.0.jar:?]
	at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) [testng-6.10.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:778) [qaf-3.0.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:632) [qaf-3.0.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39) [testng-6.10.jar:?]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421) [testng-6.10.jar:?]
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) [testng-6.10.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'U', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:86) ~[groovy-json-4.0.6.jar:4.0.6]
	at groovy.json.JsonLexer$nextToken.call(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97) ~[json-path-5.3.0.jar:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000) ~[json-path-5.3.0.jar:?]
	... 32 more
[22.05.2023] [10:18:54] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: When I verify message for updateOrderStatus "Order status updated successfully." with arguments: [Order status updated successfully.]
[22.05.2023] [10:18:54] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: User update the order status with status FAILURE
[22.05.2023] [10:18:54] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: list out all customer address details - 
[22.05.2023] [10:18:54] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:54] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:54] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given I get list of of all customer with service end point "getAllCustomerAddress" with arguments: [getAllCustomerAddress]
[22.05.2023] [10:18:56] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given I get list of of all customer with service end point "getAllCustomerAddress" with arguments: [getAllCustomerAddress]
[22.05.2023] [10:18:56] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Then I will receive valid response
[22.05.2023] [10:18:56] ERROR [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:83) - Failure Teststep: Then I will receive valid response
java.lang.AssertionError: expected [401] but found [200]
	at org.testng.Assert.fail(Assert.java:94) ~[testng-6.10.jar:?]
	at org.testng.Assert.failNotEquals(Assert.java:513) ~[testng-6.10.jar:?]
	at org.testng.Assert.assertEqualsImpl(Assert.java:135) ~[testng-6.10.jar:?]
	at org.testng.Assert.assertEquals(Assert.java:116) ~[testng-6.10.jar:?]
	at org.testng.Assert.assertEquals(Assert.java:389) ~[testng-6.10.jar:?]
	at org.testng.Assert.assertEquals(Assert.java:399) ~[testng-6.10.jar:?]
	at com.quantum.steps.ApiRegresstionTest.iWillReceiveValidResponse(ApiRegresstionTest.java:441) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:150) ~[qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:127) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:237) [qaf-3.0.0.jar:?]
	at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) [testng-6.10.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:778) [qaf-3.0.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:632) [qaf-3.0.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39) [testng-6.10.jar:?]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421) [testng-6.10.jar:?]
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) [testng-6.10.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[22.05.2023] [10:18:56] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Then I will receive valid response
[22.05.2023] [10:18:56] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: list out all customer address details with status FAILURE
[22.05.2023] [10:18:56] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: To get all customer address of the user - 
[22.05.2023] [10:18:56] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:56] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:56] ERROR [TestNG] com.qmetry.qaf.automation.step.StepNotFoundException (StepNotFoundException.java:48) - 
/**
* Auto-generated code snippet by QMetry Automation Framework.
*/
@QAFTestStep(description="I get list of of all customer  with service end point {0}")
public void iGetListOfOfAllCustomerWithServiceEndPoint(String str0){
	//TODO: remove NotYetImplementedException and call test steps
	throw new NotYetImplementedException();
}
[22.05.2023] [10:18:56] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: To get all customer address of the user with status FAILURE
[22.05.2023] [10:18:56] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: delete exsting customer details with id and user_id - 
[22.05.2023] [10:18:56] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:56] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:56] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given I delete existingcustomer details with service end point "deleteCustomerAddress" with arguments: [deleteCustomerAddress]
[22.05.2023] [10:18:57] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given I delete existingcustomer details with service end point "deleteCustomerAddress" with arguments: [deleteCustomerAddress]
[22.05.2023] [10:18:57] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: When I verify message for delete existing customer address "Address deleted successfully." with arguments: [Address deleted successfully.]
[22.05.2023] [10:18:57] ERROR [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:83) - Failure Teststep: When I verify message for delete existing customer address "Address deleted successfully." with arguments: [Address deleted successfully.]
io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202) ~[json-path-5.3.0.jar:?]
	at com.quantum.steps.ApiRegresstionTest.iVerifyMessageForDeleteExistingCustomerAddress(ApiRegresstionTest.java:377) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:150) ~[qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:127) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:237) [qaf-3.0.0.jar:?]
	at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) [testng-6.10.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:778) [qaf-3.0.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:632) [qaf-3.0.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39) [testng-6.10.jar:?]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421) [testng-6.10.jar:?]
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) [testng-6.10.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'U', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:86) ~[groovy-json-4.0.6.jar:4.0.6]
	at groovy.json.JsonLexer$nextToken.call(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97) ~[json-path-5.3.0.jar:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000) ~[json-path-5.3.0.jar:?]
	... 32 more
[22.05.2023] [10:18:57] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: When I verify message for delete existing customer address "Address deleted successfully." with arguments: [Address deleted successfully.]
[22.05.2023] [10:18:57] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: delete exsting customer details with id and user_id with status FAILURE
[22.05.2023] [10:18:57] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: Insert new customer details - 
[22.05.2023] [10:18:57] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:57] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:57] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given I insert new customer details with service end point "insertCustomerAddress" with arguments: [insertCustomerAddress]
[22.05.2023] [10:18:59] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given I insert new customer details with service end point "insertCustomerAddress" with arguments: [insertCustomerAddress]
[22.05.2023] [10:18:59] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: When I verify message for insert new customer address "Address inserted successfully." with arguments: [Address inserted successfully.]
[22.05.2023] [10:18:59] ERROR [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:83) - Failure Teststep: When I verify message for insert new customer address "Address inserted successfully." with arguments: [Address inserted successfully.]
io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202) ~[json-path-5.3.0.jar:?]
	at com.quantum.steps.ApiRegresstionTest.iVerifyMessageForInsertNewCustomerAddress(ApiRegresstionTest.java:333) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:150) ~[qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:127) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:237) [qaf-3.0.0.jar:?]
	at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) [testng-6.10.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:778) [qaf-3.0.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:632) [qaf-3.0.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39) [testng-6.10.jar:?]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421) [testng-6.10.jar:?]
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) [testng-6.10.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'U', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:86) ~[groovy-json-4.0.6.jar:4.0.6]
	at groovy.json.JsonLexer$nextToken.call(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97) ~[json-path-5.3.0.jar:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000) ~[json-path-5.3.0.jar:?]
	... 32 more
[22.05.2023] [10:18:59] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: When I verify message for insert new customer address "Address inserted successfully." with arguments: [Address inserted successfully.]
[22.05.2023] [10:18:59] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: Insert new customer details with status FAILURE
[22.05.2023] [10:18:59] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: Update exsting customer details with id and user_id - 
[22.05.2023] [10:18:59] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:59] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:18:59] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given I update customer details with service end point "updateCustomerAddress" with arguments: [updateCustomerAddress]
[22.05.2023] [10:19:00] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given I update customer details with service end point "updateCustomerAddress" with arguments: [updateCustomerAddress]
[22.05.2023] [10:19:00] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: When I verify message for update existing customer address "Address updated successfully." with arguments: [Address updated successfully.]
[22.05.2023] [10:19:00] ERROR [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:83) - Failure Teststep: When I verify message for update existing customer address "Address updated successfully." with arguments: [Address updated successfully.]
io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202) ~[json-path-5.3.0.jar:?]
	at com.quantum.steps.ApiRegresstionTest.iVerifyMessageForUpdateExistingCustomerAddress(ApiRegresstionTest.java:477) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:150) ~[qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:127) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:237) [qaf-3.0.0.jar:?]
	at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) [testng-6.10.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:778) [qaf-3.0.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:632) [qaf-3.0.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39) [testng-6.10.jar:?]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421) [testng-6.10.jar:?]
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) [testng-6.10.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'U', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:86) ~[groovy-json-4.0.6.jar:4.0.6]
	at groovy.json.JsonLexer$nextToken.call(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97) ~[json-path-5.3.0.jar:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source) ~[?:?]
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965) ~[json-path-5.3.0.jar:?]
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000) ~[json-path-5.3.0.jar:?]
	... 32 more
[22.05.2023] [10:19:00] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: When I verify message for update existing customer address "Address updated successfully." with arguments: [Address updated successfully.]
[22.05.2023] [10:19:00] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: Update exsting customer details with id and user_id with status FAILURE
[22.05.2023] [10:19:00] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:284) - 

Executing scenario: To get user address with latitude and longitude list - 
[22.05.2023] [10:19:00] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:19:00] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given set the base domain "https://suitsbackenddevelopment.azurewebsites.net/router/" with arguments: [https://suitsbackenddevelopment.azurewebsites.net/router/]
[22.05.2023] [10:19:00] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Given I get list of latitude and logutide details with service end point "getlatlong" with arguments: [getlatlong]
[22.05.2023] [10:19:01] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Given I get list of latitude and logutide details with service end point "getlatlong" with arguments: [getlatlong]
[22.05.2023] [10:19:01] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:71) - Invoking Teststep: Then I will receive valid response
[22.05.2023] [10:19:01] ERROR [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:83) - Failure Teststep: Then I will receive valid response
java.lang.AssertionError: expected [401] but found [200]
	at org.testng.Assert.fail(Assert.java:94) ~[testng-6.10.jar:?]
	at org.testng.Assert.failNotEquals(Assert.java:513) ~[testng-6.10.jar:?]
	at org.testng.Assert.assertEqualsImpl(Assert.java:135) ~[testng-6.10.jar:?]
	at org.testng.Assert.assertEquals(Assert.java:116) ~[testng-6.10.jar:?]
	at org.testng.Assert.assertEquals(Assert.java:389) ~[testng-6.10.jar:?]
	at org.testng.Assert.assertEquals(Assert.java:399) ~[testng-6.10.jar:?]
	at com.quantum.steps.ApiRegresstionTest.iWillReceiveValidResponse(ApiRegresstionTest.java:441) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:150) ~[qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:127) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174) [qaf-3.0.0.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:237) [qaf-3.0.0.jar:?]
	at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) [testng-6.10.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:778) [qaf-3.0.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:632) [qaf-3.0.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39) [testng-6.10.jar:?]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421) [testng-6.10.jar:?]
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) [testng-6.10.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[22.05.2023] [10:19:01] INFO [TestNG] com.qmetry.qaf.automation.step.TestStepListener (TestStepListener.java:91) - Completed Teststep: Then I will receive valid response
[22.05.2023] [10:19:01] INFO [TestNG] com.qmetry.qaf.automation.step.client.Scenario (Scenario.java:223) - Competed scenario: To get user address with latitude and longitude list with status FAILURE
[22.05.2023] [10:19:01] INFO [main] com.qmetry.qaf.automation.testng.pro.QAFSuiteListener (QAFTestNGListener.java:91) - Unable to create testng-failed-qas.xml
